name: Convert Notebook to README

on:
  push:
    paths:
      - 'example.ipynb'
  workflow_dispatch:

jobs:
  convert-notebook:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          
          # Install dependencies from requirements.txt
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Convert notebook to README
        run: |
          jupyter nbconvert --execute --to markdown example.ipynb --output README
      
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --staged --quiet || git commit -m "Update README.md from example.ipynb"
          git push
